version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13-browsers
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: update apt-get
          command: |
            cat /etc/apt/sources.list
            sudo rm /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian jessie main" | sudo tee -a /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "deb-src http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "Acquire::Check-Valid-Until false;" | sudo tee -a /etc/apt/apt.conf.d/10-nocheckvalid
            echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | sudo tee -a /etc/apt/preferences.d/10-archive-pin
            cat /etc/apt/sources.list
            sudo apt-get update
      - run:
          name: Install imagemagick
          command: |
            sudo apt-get install -y aptitude
            sudo apt-get --reinstall install libept1.4.12
            sudo aptitude -y install imagemagick
            sudo aptitude -y install libmagickcore-dev
            sudo aptitude -y install libmagickwand-dev
      - run:
          name: Install awscli
          working_directory: /
          command: |
            sudo apt-get -y -qq install awscli
      - run:
          name: install git-lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs=1.1.1
            git lfs install

      - restore_cache:
          keys:
          - v6-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum "bower.json" }}

      - run: npm install
      - run: rm -rf bower_components/everfi-sdk
      - run: ./node_modules/bower/bin/bower cache clean everfi-sdk
      - run: ./node_modules/bower/bin/bower install

      - save_cache:
          paths:
            - node_modules
            - bower_components
          key: v6-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum "bower.json" }}

      - run:
          command: npm test
          environment:
            PHANTOMJS_BIN: node_modules/.bin/phantomjs
      - deploy:
          name: deployment
          command: |
           if [ "${CIRCLE_BRANCH}" == "master" ] || [[ "${CIRCLE_BRANCH}" =~ release/.* ]] || [[ "${CIRCLE_BRANCH}" =~ hotfix/.* ]]; then
             ./node_modules/gulp/bin/gulp.js deploy
           elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
             ./node_modules/gulp/bin/gulp.js deploy-develop
           elif [ "${CIRCLE_BRANCH}" == "split-fixes" ]; then
             ./node_modules/gulp/bin/gulp.js deploy-custom --folder split_modules
           fi
      - run: sudo apt-get install maven
      - run: mvn test -f Demo_Maven/pom.xml
             
         
