version: 2.1

executors: 
  my-executor: 
    docker: 
      - 
        image: "selenium/standalone-chrome:3.1.0"
orbs: 
  maven: circleci/maven@0.0.11
version: 2.1
workflows: 
  maven_test: 
    jobs: 
      ? "-maven/test"
      : 
        executor: my-executor
        test_results_path: /path/to/test/results

       
       