version: 2
jobs:
  build:
  
  	type: shell
	command: |
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: ubuntu:14.04
      env:
        - DISPLAY=:99
        - CHROME_BIN=/usr/bin/google-chrome
   
    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn test
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar