version: 2.1

orbs:
  maven: circleci/maven@0.0.11

jobs:
  build:
    
    working_directory: ~/circleci-demo-java

    docker:
      - image: selenium/standalone-chrome:3.1.0
      - image: circleci/openjdk:8-jdk
      

    steps:

      - checkout
      
      - run: mvn test