version: 2.1

orbs:
  maven: circleci/maven@0.0.11
  
executors:
  my-executor:
    docker:
      - image: selenium/standalone-chrome:3.1.0
      
workflows:
  maven_test:
    jobs:
      - maven/test:
          test_results_path: /path/to/test/results